version: '3.8'

services:
  # PostgreSQL Database (Development)
  postgres-dev:
    image: postgres:15-alpine
    container_name: subway_postgres_dev
    environment:
      POSTGRES_USER: subway_user
      POSTGRES_PASSWORD: subway_pass
      POSTGRES_DB: subway_wear_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Redis (Development - Optional)
  # redis-dev:
  #   image: redis:7-alpine
  #   container_name: subway_redis_dev
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped